init: bigger revamp of init/boot logic
Adds dual-boot capability, i.e. the user can choose, with VolUp/VolDown
buttons, whether to boot Harmattan or the Alternative OS (e.g. Nemo
mobile).  Moslo now treats mmcblk0p4 as the partition for Alternative OS
(instead of mmcblk0p1). The option for Alternative OS is given, if moslo
can mount the partition and finds kernel image there, under /boot.

HACK: one quirk remains: moslo exports whole eMMC for now (instead of
the Alternative OS partition, only) as a mass storage device over USB.
This is to make repartitioning easier for the user. To be removed when
automatic re-partitioning functionality is added to moslo.

Also, changes most (if not all) messages printed onto display.

Totally rewrites kexec_load script accordingly. Also, kexec_load (that
is AltOS boot) now only requires bzImage to be present. One can
optionally provide cmdline and/or initrd file. If no cmdline file is
given, kexec_load uses /proc/cmdline.

diff --git a/usr/bin/kexec_load b/usr/bin/kexec_load
--- a/usr/bin/kexec_load
+++ b/usr/bin/kexec_load
@@ -1,12 +1,39 @@
 #!/bin/sh
 
-export MOUNT_DIR=mmcmount
-NOLO_CMD=$(cat /proc/cmdline)
-BOOT_CMD=$(ls -1r /$MOUNT_DIR/boot/cmdline*|sed -n '1p')
-MEEGO_ROOT="root=/dev/mmcblk0p1"
-MEEGO_CMD=$(sed q $BOOT_CMD)
-MOSLO_CMD=$(echo "$NOLO_CMD $MEEGO_CMD" |sed "s/root=[\./a-zA-Z0-9]* //g")
-CMD="$MOSLO_CMD $MEEGO_ROOT console=ttyS0,1152008N1"
+if [ $# -lt 1 ]; then
+    echo "Usage: $PROG <mount-dir>"
+    exit 1
+fi
 
-kexec -l /$MOUNT_DIR/boot/bzImage --command-line="$CMD"
+MOUNT_DIR=$1
+BOOT_DIR="$MOUNT_DIR/boot"
+BZIMAGE="$BOOT_DIR/bzImage"
+FALLBACK_ROOTDEV="/dev/mmcblk0p4"
 
+INITRD=""
+CMDLINE=""
+ORIG_CMDLINE="`cat /proc/cmdline`"
+
+if [ -f "$BZIMAGE" ]; then
+    if [ -f "$BOOT_DIR/initrd" ]; then
+        echo "Found initrd"
+        # use quoting and eval (later) to handle whitespace
+        INITRD="\"--initrd=$BOOT_DIR/initrd\""
+    fi
+    if [ -f "$BOOT_DIR/cmdline" ]; then
+        echo "Found cmdline, appending that to the original cmdline"
+        # use quoting and eval (later) to handle whitespace
+        CMDLINE="--command-line=\"$ORIG_CMDLINE `cat $BOOT_DIR/cmdline`\""
+    else
+        echo "No cmdline file found, appending \"root=$FALLBACK_ROOTDEV\" to the original cmdline"
+        CMDLINE="--command-line=\"$ORIG_CMDLINE root=$FALLBACK_ROOTDEV\""
+    fi
+    # use eval to handle emtpy arguments gracefully
+    echo "Using $CMDLINE"
+    eval "kexec -l  $INITRD $CMDLINE $BZIMAGE"
+    exit $?
+else
+    echo "kexec_load failed: bzImage not found"
+fi
+
+exit 1
